CMaize Startup and Project Class
CMakePP/CMaize pull request #123
Opened 2023-09-19 15:50 UTC by ryanmrichard

**Is this pull request associated with an issue(s)?**
No

**Description**
This PR writes up some notes about what happens when CMaize is included by the user and describes the design of the ``CMaizeProject`` class (an instance of which is created when CMaize is loaded).

**TODOs**
- [ ] Document ``CMaizeProject``.

2023-09-20 20:57 UTC, ryanmrichard commented
@zachcran I'm looking at the `CMaizeProject` class. Do we track which targets are from dependencies and which are part of the project? In particular, I assume that in general the `build_targets` field will contain a mix of targets that may have either come from a dependency or the project? I also assume that the `installed_targets` field will only contain dependency targets (because I don't know how you have an installed version of the project you're building already).

2023-09-20 21:31 UTC, zachcran commented
>Do we track which targets are from dependencies and which are part of the project?

I don't think we differentiate between targets generated from dependencies and targets generated from projects. `installed_targets` will likely only have dependency targets for the same reasons you gave, but `build_targets` can have both project and dependency targets in it.

2023-09-21 19:00 UTC, ryanmrichard commented
I think this is r2g. I ultimately decided to combine the CMaizeProject and PackageSpecification components into one component (which I just refer to as the CMaizeProject component). This is how the source is laid out anyways. If we stuck with the previous design the CMaizeProject component would just be a single class (PackageSpecification would have been too, though I could see that evolving). This PR did result in some TODOs in #123.

2023-09-22 22:18 UTC, zachcran requested changes

2023-09-22 22:18 UTC, zachcran commented on docs/src/developer/design/assets/cmaize_project.png
For the PackageSpecification note, it took me a few reads to understand "Input consumers of package provide to a PackageManager" here. Maybe "Provided to a PackageManager to get back the installed version of the package" would be clearer, if that still captures the message you are looking for.

In the PackageSpecification note, you also say "installed version of this project", which I think should be "installed version of this package".

2023-09-22 22:18 UTC, zachcran commented on docs/src/developer/design/cmaize_project.rst
> +component is designed to collect the the project's properties into a single
```suggestion
component is designed to collect the project's properties into a single
```

2023-09-22 22:18 UTC, zachcran commented on docs/src/developer/design/cmaize_project.rst
> +``CMaizeProject`` object's state and  to this end we introduce
```suggestion
``CMaizeProject`` object's state and to this end we introduce
```

2023-09-25 18:29 UTC, merged